/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROPOSTA_H_RPCGEN
#define _PROPOSTA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct argDir {
	char *nomedir;
	int soglia;
};
typedef struct argDir argDir;

struct resultFileScan {
	int numchar;
	int numword;
	int numline;
};
typedef struct resultFileScan resultFileScan;

#define PROPOSTAPROG 0x20000013
#define PROPOSTAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILE_SCAN 1
extern  resultFileScan * file_scan_1(char **, CLIENT *);
extern  resultFileScan * file_scan_1_svc(char **, struct svc_req *);
#define DIR_SCAN 2
extern  int * dir_scan_1(argDir *, CLIENT *);
extern  int * dir_scan_1_svc(argDir *, struct svc_req *);
extern int propostaprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILE_SCAN 1
extern  resultFileScan * file_scan_1();
extern  resultFileScan * file_scan_1_svc();
#define DIR_SCAN 2
extern  int * dir_scan_1();
extern  int * dir_scan_1_svc();
extern int propostaprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_argDir (XDR *, argDir*);
extern  bool_t xdr_resultFileScan (XDR *, resultFileScan*);

#else /* K&R C */
extern bool_t xdr_argDir ();
extern bool_t xdr_resultFileScan ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROPOSTA_H_RPCGEN */
