/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proposta.h"

bool_t
xdr_argDir (XDR *xdrs, argDir *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nomedir, 125))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->soglia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultFileScan (XDR *xdrs, resultFileScan *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numchar))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numword))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numline))
		 return FALSE;
	return TRUE;
}
